import React from 'react'

import Pixel from './Pixel'

const App = () => {
  return  [
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
    <Pixel />,
  ]
}

export default App