import React from 'react'

import Pixel from './Pixel.jsx'

const App = () => {
  return (
    <div>
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
      <Pixel />
    </div>
  )
}

export default App
